version: '3.4'

services:
  3drcan:
    image: 3drcan
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 train.py "]
    ports:
      - 5678:5678
